---
require:
  - rubocop-rspec
  - rubocop-rails
AllCops:
  Exclude:
    - db/schema.rb
    - bin/**/*
    - vendor/**/*
  NewCops: enable
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Layout/LineLength:
  Enabled: false
Rails/NotNullColumn:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
