---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: senior-accounts
spec:
  selector:
    matchLabels:
      app: senior-accounts
  template:
    metadata:
      labels:
        app: senior-accounts
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: rails
          image: quay.io/realliance/senior-accounts:latest@sha256:17692aee6cb16d470c3909ba88c6a66cb494b9432a4ba0643a43e9fb08ce2fea
          ports:
            - containerPort: 8080
          env:
            - name: PG_HOST
              value: acid-senior-accounts
            - name: PG_DATABASE
              value: senior_accounts
            - name: PG_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rails.acid-senior-accounts.credentials
                  key: username
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rails.acid-senior-accounts.credentials
                  key: password
            - name: RAILS_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: rails-env
                  key: master-key
---
apiVersion: v1
kind: Service
metadata:
  name: senior-accounts
spec:
  selector:
    app: senior-accounts
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
