---
resource_types:
  - name: pull-request
    type: registry-image
    source:
      repository: docker.io/teliaoss/github-pr-resource
resources:
  - name: pull-request
    type: pull-request
    icon: source-branch
    check_every: 1m
    source:
      repository: realliance/senior-accounts
      access_token: ((github-access-token))
      disable_ci_skip: true
  - name: senior-accounts-main
    type: git
    icon: git
    source:
      uri: https://github.com/realliance/senior-accounts
      branch: main
  - name: quay
    type: registry-image
    icon: docker
    source:
      repository: quay.io/realliance/senior-accounts
      tag: latest
      username: ((quay-ci-account.username))
      password: ((quay-ci-account.token))
  - name: ruby
    type: registry-image
    icon: docker
    source:
      repository: docker.io/ruby
  - name: python
    type: registry-image
    icon: docker
    source:
      repository: docker.io/python
  - name: oci-build-task
    type: registry-image
    icon: docker
    source:
      repository: docker.io/vito/oci-build-task
jobs:
  - name: validate-pr
    plan:
      - get: pull-request
        trigger: true
        version: every
      - put: pull-request
        params:
          path: pull-request
          status: pending
      - get: ruby
      - get: python
      - in_parallel:
          - task: rubocop
            image: ruby
            config:
              platform: linux
              inputs:
                - name: pull-request
                  path: .
              caches:
                - path: vendor
              run:
                path: /bin/sh
                args:
                  - -exc
                  - |
                    bundle config set --local path './vendor'
                    bundle install
                    bundle exec rubocop
          - task: rspec
            image: ruby
            config:
              platform: linux
              inputs:
                - name: pull-request
                  path: .
              outputs:
                - name: coverage
                  path: pull-request/coverage
              caches:
                - path: vendor
              run:
                path: /bin/sh
                args:
                  - -exc
                  - |
                    bundle config set --local path './vendor'
                    bundle install
                    bundle exec rails spec
          - task: database-consistency
            image: ruby
            config:
              platform: linux
              inputs:
                - name: pull-request
                  path: .
              caches:
                - path: vendor
              run:
                path: /bin/sh
                args:
                  - -exc
                  - |
                    bundle config set --local path './vendor'
                    bundle install
                    bundle exec database_consistency
          - task: yamllint
            image: python
            config:
              platform: linux
              inputs:
                - name: pull-request
                  path: .
              caches:
                - path: cache
              run:
                path: /bin/sh
                args:
                  - -exc
                  - |
                    pip install --cache-dir ./cache yamllint
                    yamllint .
        on_failure:
          put: pull-request
          params:
            path: pull-request
            status: failure
      - put: pull-request
        params:
          path: pull-request
          status: success
  - name: set-pipeline
    plan:
      - get: senior-accounts-main
        trigger: true
      - set_pipeline: self
        file: senior-accounts-main/ci/ci.yaml
  - name: publish
    plan:
      - get: senior-accounts-main
        trigger: true
      - get: oci-build-task
      - load_var: git-commit
        file: senior-accounts-main/.git/ref
        reveal: true
      - task: build
        privileged: true
        image: oci-build-task
        params:
          BUILD_ARG_COMMIT: ((.:git-commit))
        config:
          platform: linux
          inputs:
            - name: senior-accounts-main
              path: .
          outputs:
            - name: image
          caches:
            - path: cache
          run:
            path: build
      - put: quay
        params:
          image: image/image.tar
