---
name: Auto-Merge
# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: 0 * * * *
  check_suite:
    types:
      - completed
  pull_request_review:
    types:
      - submitted
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: reitermarkus/automerge@v1
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          merge-method: squash
          squash-title: true
