---
<<<<<<< HEAD
name: Bypass Auto Approval
# yamllint disable-line rule:truthy
on:
  pull_request_target:
    types: [opened]
    branches: [main]
jobs:
  bypass-approve:
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@1.0.0
        if: github.actor == 'ConnorJC3'
=======
name: Comment Auto Approval
# yamllint disable-line rule:truthy
on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]
jobs:
  comment-approve:
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@1.0.0
>>>>>>> d6191ef (New workflow)
        id: check
        with:
          trigger: '!approve'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: hmarr/auto-approve-action@v2.0.0
<<<<<<< HEAD
        if: steps.check.outputs.triggered == 'true'
=======
        if: github.actor == 'ConnorJC3' && steps.check.outputs.triggered == 'true'
>>>>>>> d6191ef (New workflow)
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
