---
name: Renovate Auto Approval
# yamllint disable-line rule:truthy
on:
  pull_request_target:
    branches: [main]
    paths: [deploy]
jobs:
  renovate-approve:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v2.0.0
        if: github.actor == 'realliance-ci'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
